### ISSUE TITLE
Display Gloria Patri with full introit

### ISSUE THREAD

**Issue by sethborders** [bbloomf/jgabc#16]
perhaps another option could be added to the drop down "Full w/ G. P." where it replaces the "e u o u a e" with the Gloria Patri tone

**Comment by bbloomf** [comment]
Oh, sure.  That probably would be helpful to have as an option.  Especially for mode 6.

**Comment by sethborders** [comment]
I haven't had a chance to actually try changing anything yet, but looking through your code, lines 692 to 701 where it uses psalmToneIntroitGloriaPatri() look promising. I guess we need to make a new function to do something similar but on the full score.

**Comment by bbloomf** [comment]
I just made a commit to the gh-pages branch that adds this feature.  I haven't tested it extensively, so please let me know if you find any problems with it.

**Comment by sethborders** [comment]
Perfect! Thanks
