### ISSUE TITLE
Wrong Offertory for Mass 26. November

### ISSUE THREAD

**Issue by bartlech** [bbloomf/jgabc#18]
Hello, 
first of all big thank you for work you have done. Unfortunately when I generated propers for today's Mass (26 Nov, Saint Sylvester) I realized, that there is a mistake. Offertory should be "Desiderium animae eius", but there is "Desiderium pauperum". Could you correct this?
Thank you for your response.

**Comment by sethborders** [comment]
Thanks for pointing this out.
none of this work was reviewed so there was bound to be some mistakes.  I'll get on fixing it asap

in the meantime, you can work around the issue from the menu "Select another Mass... > Custom" and entering all the proper incipits manually.
