### ISSUE TITLE
accented vowels not detected

### ISSUE THREAD

**Issue by sethborders** [bbloomf/jgabc#28]
on transcriber.html

try this notation:
```
initial-style: 1;
%%
c4 ed g hj jji hg hi hg g. ;
g ijk j ji hg h gf e.d. :
dh h' g hiwji hg hi. hg g. ;
h h' g fe d efg fe e. ::
```

with this text
```
Novàne das lucem Deus,
Nos inchoàre? nec reis
Jus est petèndi, nec decet
Optàre devòtos tibi.
```

it dosent work quite right. it lines up if you replace the accents with regular vowels though

**Comment by sethborders** [comment]
i read the about page. use an apostrophe for  accents. sorry

**Comment by bbloomf** [comment]
No problem.  It might be useful in some cases to recognize vowels with any diacritical mark whatever.  I think right now it only recognizes vowels marked with an acute accent or a diaeresis.
