### ISSUE TITLE
Provide new function for "Psalms tones"

### ISSUE THREAD

**Issue by mimo38** [bbloomf/jgabc#32]
Excuse my bad English, but is it possible to add a function to repeat the first psalm verse, or a "format verse" full-tex (tex-plain) to introduce a psalm in a tex document (and download all psalms in full-tex !) ?
Thank you to your work !

**Comment by bbloomf** [comment]
I'm not certain what you're asking for.

Are you just asking for an option to start the verses with the first verse instead of the second?

That would be easy enough to add.

**Comment by mimo38** [comment]
Yes it is just it. As it exists "gabc-plain", starting with the first verse :
![capture d ecran 2019-01-17 a 19 01 23](https://user-images.githubusercontent.com/12458526/51338654-b4a48280-1a8a-11e9-8a3f-4ab027b3b20b.png)

**Comment by mimo38** [comment]
Do you need more detail ?

**Comment by bbloomf** [comment]
No, I just forgot about this in the midst of some other things I was working on.

I just added a new checkbox "GABC for first verse" which will control whether the first verse is forced to be run as GABC instead of the selected format.  Simply uncheck this box, and then click Download ZIP.

**Comment by mimo38** [comment]
Thank you ! It’s a real time saver for me!
