### ISSUE TITLE
Propers of Sts Patrick and Benedict not using Tract during Lent

### ISSUE THREAD

**Issue by cwrinn** [bbloomf/jgabc#33]
Should both use [*Beatus vir*](https://gregobase.selapa.net/chant.php?id=7670)

If I get a chance, pretty sure I can add it. However been extremely busy with software launches recently.

**Comment by bbloomf** [comment]
Thanks.  This was actually a regression; they were coded correctly, but now also reference the common, and because these feasts only occur during lent, there was a bug that was causing it to use the throughout the year propers instead of the after septuagesima propers.
