### ISSUE TITLE
Psalm texts deleted after exclamation point

### ISSUE THREAD

**Issue by mortonsc** [bbloomf/jgabc#45]
The psalm tone tool omits all text from an exclamation point to the end of the hemistich. Found this on verse 5 of psalm 119, `Heu mihi! quia incolátus meus prolongátus est: † habitávi cum habitántibus Cedar: * multum íncola fuit ánima mea.` Experimented a bit and confirmed it happens whenever there's an exclamation point in the psalm text.
![Screenshot from 2019-10-31 20-53-02](https://user-images.githubusercontent.com/3230614/68001246-8a3e4300-fc20-11e9-9774-3b157e30ef2e.png)

**Comment by bbloomf** [comment]
Thanks.  This should be fixed now.
