### ISSUE TITLE
Warning message in GABC Transcription Tool

### ISSUE THREAD

**Issue by amadiago** [bbloomf/jgabc#52]
When using the web inspector tool in the GABC Transcription Tool it shows the following warning message under the console:

> **"DevTools failed to load SourceMap: Could not load content for https://bbloomf.github.io/jgabc/exsurge.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE".**

This issue has replaced the Crimson font and default text size and has inhabilitated several settings such as "%drop-cap-text-color: ;", "%font-family: ;" and others.

**Comment by bbloomf** [comment]
Thank you.  This should be fixed now.
