### ISSUE TITLE
ocba crashes exsurge

### ISSUE THREAD

**Issue by olivierberten** [bbloomf/jgabc#53]
It's an exsurge bug but frmatthew's version doesn't have that bug and there's no issue tracker on your fork.

`<i>om</i>(h)<i>nis</i>(ih gr[ocba:1{]) <b>ter</b>(gf[ocba:0}])ra.(e)`
Actually, only the first one causes the crash. If you put ocb instead it works. Changing the 2nd one to ocba doesn't have any consequence.

With your transcription tools, the script just stop rendering anything more. But in the Source & Summit Editor the whole page gets blank.

**Comment by bbloomf** [comment]
Thanks so much; this is fixed here now, and the source and summit fix will be deployed shortly.
