### ISSUE TITLE
Broken psalm-toned Alleluia

### ISSUE THREAD

**Issue by electrodude** [bbloomf/jgabc#64]
If I select `Psalm Toned` for the Alleluia ([link](https://bbloomf.github.io/jgabc/propers.html#communioVerses=1#sunday=Pent8#styleAlleluia=psalm-tone2#styleGraduale=psalm-tone#styleIntroitus=psalm-tone#styleTractus=psalm-tone;1f#styleOffertorium=psalm-tone#styleCommunio=psalm-tone)), it includes an extra set of double bar lines containing just `ij` between the Alleluia and the verse:
![image](https://user-images.githubusercontent.com/8943110/182007922-52638db3-68f4-4a79-b4c0-fdc4545d9d0a.png)

If I select `Completely Psalm Toned` for the Alleluia ([link](https://bbloomf.github.io/jgabc/propers.html#communioVerses=1#sunday=Pent8#styleAlleluia=psalm-tone1;1f#styleGraduale=psalm-tone1#styleIntroitus=psalm-tone#styleTractus=psalm-tone;1f#styleOffertorium=psalm-tone#styleCommunio=psalm-tone)), there's no Alleluia at all - it starts with the `ij` (with the "i" as a drop cap!) and goes right into the verse:
![image](https://user-images.githubusercontent.com/8943110/182007956-3a7158ce-c509-43d8-b72c-a4ffbc2a23e6.png)

This doesn't happen for the 14th Sunday after Pentecost, but I tried some others (including all the Sundays after Pentecost) and it happens for them.

**Comment by bbloomf** [comment]
Thank you so much for letting me know about this.  I am fixing it now.  It had to do with the way some alleluias had the ij marked in gregobase.
