### ISSUE TITLE
Outdated version on the Google Play Store?

### ISSUE THREAD

**Issue by jwt2706** [bbloomf/jgabc#81]
Hey, thanks for the tool its been super helpful!

I just got a new phone recently (android 14) and I tried to download the app from the Play Store and it says that "This app isn't available for your device because it was made for an older version of Android."

The latest release from the Play Store seems to be from Jul 31, 2022. I was just wondering if there was a reason hasn't been updated yet or not.

Thanks! :D

**Comment by bbloomf** [comment]
I just haven't had time lately, and the [web version](https://bbloomf.github.io/jgabc/propers) works on mobile phones (though I suppose it requires an active Internet connection, which is the only advantage of the app)

**Comment by jwt2706** [comment]
@bbloomf Thanks for the quick response. That makes sense, and I understand that you're probably busy.

I have a suggestion though, do you think it might be worth setting up a Github Actions workflow to automatically compile an APK and just leave it in the Releases tab here on Github? That way some people could still install new version if they want, while not having to worry about updating the version on the Play Store?
I would be happy to help set that up if you think its worthwhile.

**Comment by bbloomf** [comment]
Sure, if you think that makes sense.  I was also wondering if making the web version into a progressive web app would be worthwhile, since I think that would also be useful for iOS devices.

**Comment by jwt2706** [comment]
@bbloomf Alright sounds good. I'll try to look into this and make a PR when its ready.
Also, PWAs are great but they're limited when used offline since they rely on cache. In my experience I would still be able to open PWA apps without a connection, but if I tried to load new content that I never opened while online, it wouldn't work. Maybe it's still better than nothing? I know that sideloading exists on iOS, although I've never used it before so I don't know what the limits to that are.
